---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dynasisw/public_html/sis_new/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
